### PR TITLE
LOG-13509 remove support info

### PR DESCRIPTION
**Pull request by rsheng-r7**

### CODE REVIEW

**Comment by sbialkowski-r7** [comment]
missed
https://github.com/rapid7/r7insight_ruby/blob/5365213e2a4edc2c27701665c168f1c1e6954988/r7insight.gemspec#L20

**Comment by rsheng-r7** [comment]
> missed
> https://github.com/rapid7/r7insight_ruby/blob/5365213e2a4edc2c27701665c168f1c1e6954988/r7insight.gemspec#L20

not sure it'll break anything if removed?

**Comment by rjacobs-r7** [comment]
@rsheng-r7 Nope, you won't :) That's just the e-mail address that shows up on RubyGems (and it'll only take effect once a new package is published to RubyGems).

**Comment by rjacobs-r7** [comment]
As in it won't break if you replace it with the new one. You probably do need a value there. platformsupport@rapid7.com is correct afaik.

**Comment by sbialkowski-r7** [comment]
Would `InsightOpsTeam@rapid7.com` not be more applicable?
Support aren' the owner of the package and don't want the email advertised

**Comment by rsheng-r7** [comment]
do we have an agreement yet? there are other projects that have similar cases. r7docker  `LABEL maintainer="Rapid 7 - Platform Support <platformsupport@rapid7.com>"` .  should these all be replaced with one email address?

**Comment by sbialkowski-r7** [comment]
I would say where you have `Contact Support` you remove it but where you absolutely need to put a value, use `InsightOpsTeam@rapid7.com`.
Wait for Robin to weigh in tho

**Comment by sbialkowski-r7** [comment]
> missed
> https://github.com/rapid7/r7insight_ruby/blob/5365213e2a4edc2c27701665c168f1c1e6954988/r7insight.gemspec#L20

Replace with InsightOpsTeam@rapid7.com

**Pull request merged**
